server:
  port: 8002

spring:
  application:
    name: stream-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: / #虚拟主机
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: localhost # 服务器IP
                port: 5672  # 服务器端口
                username: guest # 用户名
                password: guest # 密码
      bindings: #服务的整合处理
        mobile-out-0:
          destination: mobileExchange #studyExchange  自定义一个通道的名称
          content-type: application/json #设置消息类型，本次为json，文本则设置"text/plain"
        email-out-0:
          destination: emailExchange #studyExchange  自定义一个通道的名称
          content-type: application/json #设置消息类型，本次为json，文本则设置"text/plain"
        send-in-0: #消费者通道的名称
          destination: studyExchange #studyExchange  自定义一个通道的名称
          content-type: application/json #设置消息类型，本次为json，文本则设置"text/plain"
          group: ijustecA  # 自定义 分组名称
eureka:
  instance:
    prefer-ip-address: true  #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: #设置服务注册中心地址，集群环境
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
