server:
  port: 8762
spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456

# 配置eureka server 注册中心,单节点配置
#eureka:
#  instance:
#    hostname: localhost  #主机名
#  client:
#    register-with-eureka: false  #将自己注册到注册中心，默认为true（集群模式为true，单节点需关闭）
#    fetch-registry: false  #是否从注册中心获取服务注册信息，默认为true（集群模式为true，单节点需关闭）
#    service-url:  #注册中心对外暴露的注册地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

#配置eureka server 注册中心，集群配置
eureka:
  instance:
    hostname: eureka02  #主机名
    prefer-ip-address: true #是否使用ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
    #设置服务注册中心，指向另一个注册中心
    service-url:  #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/